name: "Update Actions"

on:
  workflow_dispatch:
  schedule:
  - cron: 0 21 * * 5

jobs:
  update-actions:
    if: ${{ github.repository == 'AlexMan123456/github-actions' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      
      - name: Update GitHub Actions
        run: npx actions-up -y

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.PAT_GITHUB }}
          branch: alex-up-bot/update-dependencies
          base: main
          commit-message: Update dependencies
          title: "Update dependencies"
