name: "Update Actions"

on:
  workflow_dispatch:
  schedule:
  - cron: 0 21 * * 5

jobs:
  update-actions:
    if: ${{ github.repository == 'AlexMan123456/github-actions' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      
      - name: Update GitHub Actions
        run: npx actions-up -y

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          token: ${{ secrets.PAT_GITHUB }}
          branch: alex-up-bot/update-dependencies
          base: main
          commit-message: Update dependencies
          title: "Update dependencies"
